/**
 * Blanner HTTP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorError } from './errorError';


/**
 * Represents error object
 */
export interface ModelError { 
    error: ErrorError;
}

