/**
 * Blanner HTTP API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProviderImportTransaction { 
    /**
     * Index of the bookable transaction.
     */
    index: number;
    receipt_date: string;
    booked_at: string;
    description: string;
    amount: number;
    debit_account: string;
    credit_account: string;
    reference: string;
}

