/**
 * Blanner HTTP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParameterCodec,
  HttpParams,
  HttpResponse
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { ProviderImportTransaction } from '../model/providerImportTransaction';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class ImportService {

  protected basePath = 'http://localhost:8123/api/v1';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
      if (firstBasePath != undefined) {
        basePath = firstBasePath;
      }

      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }


  // @ts-ignore
  private addToHttpParams(
    httpParams: HttpParams,
    value: any,
    key?: string
  ): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(
        httpParams,
        value
      );
    } else {
      httpParams = this.addToHttpParamsRecursive(
        httpParams,
        value,
        key
      );
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(
    httpParams: HttpParams,
    value?: any,
    key?: string
  ): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach(elem => httpParams = this.addToHttpParamsRecursive(
          httpParams,
          elem,
          key
        ));
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(
            key,
            (value as Date).toISOString().substring(
              0,
              10
            )
          );
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(k => httpParams = this.addToHttpParamsRecursive(
          httpParams,
          value[k],
          key != null ? `${key}.${k}` : k
        ));
      }
    } else if (key != null) {
      httpParams = httpParams.append(
        key,
        value
      );
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Imports provider-specific journal transactions.
   * Imports provider-specific journal transactions and returns a list of actually bookable transactions.
   * @param provider Provider
   * @param bookId Book ID to get bookable transactions for.
   * @param body Provider journal file data to import.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to overview-print request and response progress.
   */
  public transactionsProviderImport(
    provider: 'lexware',
    bookId: string,
    body: Blob,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json',
      context?: HttpContext,
      transferCache?: boolean
    }
  ): Observable<Array<ProviderImportTransaction>>;
  public transactionsProviderImport(
    provider: 'lexware',
    bookId: string,
    body: Blob,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json',
      context?: HttpContext,
      transferCache?: boolean
    }
  ): Observable<HttpResponse<Array<ProviderImportTransaction>>>;
  public transactionsProviderImport(
    provider: 'lexware',
    bookId: string,
    body: Blob,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json',
      context?: HttpContext,
      transferCache?: boolean
    }
  ): Observable<HttpEvent<Array<ProviderImportTransaction>>>;
  public transactionsProviderImport(
    provider: 'lexware',
    bookId: string,
    body: Blob,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json',
      context?: HttpContext,
      transferCache?: boolean
    }
  ): Observable<any> {
    if (provider === null || provider === undefined) {
      throw new Error('Required parameter provider was null or undefined when calling transactionsProviderImport.');
    }
    if (bookId === null || bookId === undefined) {
      throw new Error('Required parameter bookId was null or undefined when calling transactionsProviderImport.');
    }
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling transactionsProviderImport.');
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (provider !== undefined && provider !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>provider,
        'provider'
      );
    }
    if (bookId !== undefined && bookId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>bookId,
        'book_id'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = [
        'application/json'
      ];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let localVarTransferCache: boolean | undefined = options && options.transferCache;
    if (localVarTransferCache === undefined) {
      localVarTransferCache = true;
    }


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/octet-stream'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Content-Type',
        httpContentTypeSelected
      );
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/transactions/provider-import`;
    return this.httpClient.request<Array<ProviderImportTransaction>>(
      'post',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: body,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress
      }
    );
  }

}
